CREATE DATABASE IF NOT EXISTS demo;
USE demo;
DROP TABLE IF EXISTS Users;

CREATE TABLE IF NOT EXISTS Users (
  user_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  age INT,
  gender VARCHAR(10),
  country VARCHAR(200),
  subscription VARCHAR(20)
)